export const UPLOAD_VIDEO = 'UPLOAD_VIDEO';
export const UPLOAD_AUDIO = 'UPLOAD_AUDIO';
export const UPLOAD_IMAGES = 'UPLOAD_IMAGES';
export const CHECK_SIGNATURE_FILES_UPLOADED = 'CHECK_SIGNATURE_FILES_UPLOADED';
export const SET_VIDEO_UPLOAD_STATUS = 'SET_VIDEO_UPLOAD_STATUS';
export const SET_AUDIO_UPLOAD_STATUS = 'SET_AUDIO_UPLOAD_STATUS';
export const SET_IMAGES_UPLOAD_STATUS = 'SET_IMAGES_UPLOAD_STATUS';
export const ATTACH_CONTRACT_FILES = 'ATTACH_CONTRACT_FILES';
